# Generated by Django 5.1 on 2024-11-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recommended_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
