# Generated by Django 5.1 on 2024-11-25 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0003_alter_enrollment_status'),
        ('user', '0003_remove_customuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_marks', models.PositiveIntegerField()),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='marks.heading')),
            ],
        ),
        migrations.CreateModel(
            name='MarksEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_entries', to='marks.subcategory')),
            ],
        ),
    ]
