# Generated by Django 5.1 on 2024-11-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksentry',
            name='marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
