# Generated by Django 5.1 on 2024-12-02 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0004_section_finalized'),
        ('user', '0003_remove_customuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField()),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('starred', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'unique_together': {('student', 'section', 'request_text')},
            },
        ),
    ]
